services:
  deadman-notifier:
    build: .
    image: ghcr.io/coralbits/deadmannotifier:latest
    container_name: deadman-notifier
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
